### ISSUE TITLE
[REQUEST] Sideload files

### ISSUE THREAD

**Issue by simanchaltheboss** [infinitepower18/WSA-Sideloader#106] opened 2024-02-07 19:24 UTC
### Describe your request

Integrate 'adb push' to allow easy side-loading files or anything in addition to apk's with option to select the specific location of WSA

**Comment by infinitepower18** [comment] 2024-02-07 19:29
Thank you for your suggestion.
As this is a duplicate of #78 I am closing this one. Please refer to the other issue for further updates.

**Closed by infinitepower18** 2024-02-07 19:29 UTC
Labels: enhancement
